In [1]:
#From Github
# Credits: https://medium.com/towards-entrepreneurship/importing-a-csv-file-from-github-in-a-jupyter-notebook-e2c28e7e74a5
import pandas as pd
import requests
import io

url = "https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv" # Make sure the url is the raw version of the file on GitHub

download = requests.get(url).content

# Reading the downloaded content and turning it into a pandas dataframe

df = pd.read_csv(io.StringIO(download.decode('utf-8')))

# Printing out the first 5 rows of the dataframe

print (df.head())

  iso_code continent     location        date  total_cases  new_cases  \
0      AFG      Asia  Afghanistan  2020-02-24          5.0        5.0
1      AFG      Asia  Afghanistan  2020-02-25          5.0        0.0
2      AFG      Asia  Afghanistan  2020-02-26          5.0        0.0
3      AFG      Asia  Afghanistan  2020-02-27          5.0        0.0
4      AFG      Asia  Afghanistan  2020-02-28          5.0        0.0

   new_cases_smoothed  total_deaths  new_deaths  new_deaths_smoothed  ...  \
0                 NaN           NaN         NaN                  NaN  ...
1                 NaN           NaN         NaN                  NaN  ...
2                 NaN           NaN         NaN                  NaN  ...
3                 NaN           NaN         NaN                  NaN  ...
4                 NaN           NaN         NaN                  NaN  ...

   male_smokers  handwashing_facilities  hospital_beds_per_thousand  \
0           NaN                  37.746                         0.5
1           NaN                  37.746                         0.5
2           NaN                  37.746                         0.5
3           NaN                  37.746                         0.5
4           NaN                  37.746                         0.5

   life_expectancy  human_development_index  population  \
0            64.83                    0.511  41128772.0
1            64.83                    0.511  41128772.0
2            64.83                    0.511  41128772.0
3            64.83                    0.511  41128772.0
4            64.83                    0.511  41128772.0

   excess_mortality_cumulative_absolute  excess_mortality_cumulative  \
0                                   NaN                          NaN
1                                   NaN                          NaN
2                                   NaN                          NaN
3                                   NaN                          NaN
4                                   NaN                          NaN

   excess_mortality  excess_mortality_cumulative_per_million
0               NaN                                      NaN
1               NaN                                      NaN
2               NaN                                      NaN
3               NaN                                      NaN
4               NaN                                      NaN

[5 rows x 67 columns]

In [3]:
df.columns

Index(['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases',
       'new_cases_smoothed', 'total_deaths', 'new_deaths',
       'new_deaths_smoothed', 'total_cases_per_million',
       'new_cases_per_million', 'new_cases_smoothed_per_million',
       'total_deaths_per_million', 'new_deaths_per_million',
       'new_deaths_smoothed_per_million', 'reproduction_rate', 'icu_patients',
       'icu_patients_per_million', 'hosp_patients',
       'hosp_patients_per_million', 'weekly_icu_admissions',
       'weekly_icu_admissions_per_million', 'weekly_hosp_admissions',
       'weekly_hosp_admissions_per_million', 'total_tests', 'new_tests',
       'total_tests_per_thousand', 'new_tests_per_thousand',
       'new_tests_smoothed', 'new_tests_smoothed_per_thousand',
       'positive_rate', 'tests_per_case', 'tests_units', 'total_vaccinations',
       'people_vaccinated', 'people_fully_vaccinated', 'total_boosters',
       'new_vaccinations', 'new_vaccinations_smoothed',
       'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred',
       'people_fully_vaccinated_per_hundred', 'total_boosters_per_hundred',
       'new_vaccinations_smoothed_per_million',
       'new_people_vaccinated_smoothed',
       'new_people_vaccinated_smoothed_per_hundred', 'stringency_index',
       'population_density', 'median_age', 'aged_65_older', 'aged_70_older',
       'gdp_per_capita', 'extreme_poverty', 'cardiovasc_death_rate',
       'diabetes_prevalence', 'female_smokers', 'male_smokers',
       'handwashing_facilities', 'hospital_beds_per_thousand',
       'life_expectancy', 'human_development_index', 'population',
       'excess_mortality_cumulative_absolute', 'excess_mortality_cumulative',
       'excess_mortality', 'excess_mortality_cumulative_per_million'],
      dtype='object')

In [5]:
df.shape

(261499, 67)

In [6]:
df1=df[['date','location','total_cases']]

In [8]:
df1.shape

(261499, 3)

In [44]:
df2 = df1[df1['date'] == "2023-02-28"]
df2

              date                          location  total_cases
1100    2023-02-28                       Afghanistan       209322
2215    2023-02-28                            Africa     12518681
3318    2023-02-28                           Albania       334391
4421    2023-02-28                           Algeria       271441
5518    2023-02-28                           Andorra        47866
6597    2023-02-28                            Angola       105255
7668    2023-02-28                          Anguilla         3904
8754    2023-02-28               Antigua and Barbuda         9106
9912    2023-02-28                         Argentina     10044125
11037   2023-02-28                           Armenia       446819
12123   2023-02-28                             Aruba        44026
13260   2023-02-28                              Asia    210545430
14393   2023-02-28                         Australia     11366361
15496   2023-02-28                           Austria      5911294
16594   2023-02-28                        Azerbaijan       828548
17677   2023-02-28                           Bahamas        37491
18781   2023-02-28                           Bahrain       707480
19872   2023-02-28                        Bangladesh      2037773
20954   2023-02-28                          Barbados       106645
22054   2023-02-28                           Belarus       994037
23178   2023-02-28                           Belgium      4717655
24254   2023-02-28                            Belize        70757
25337   2023-02-28                             Benin        27990
26417   2023-02-28                           Bermuda        18799
27510   2023-02-28                            Bhutan        62615
28598   2023-02-28                           Bolivia      1193009
29664   2023-02-28   Bonaire Sint Eustatius and Saba        11797
30758   2023-02-28            Bosnia and Herzegovina       401575
31827   2023-02-28                          Botswana       329727
32929   2023-02-28                            Brazil     37052936
34000   2023-02-28            British Virgin Islands         7305
35090   2023-02-28                            Brunei       277992
36181   2023-02-28                          Bulgaria      1296853
37270   2023-02-28                      Burkina Faso        22056
38338   2023-02-28                           Burundi        53609
39470   2023-02-28                          Cambodia       138717
40563   2023-02-28                          Cameroon       124392
41699   2023-02-28                            Canada      4602806
42778   2023-02-28                        Cape Verde        63244
43864   2023-02-28                    Cayman Islands        31472
44948   2023-02-28          Central African Republic        15368
46028   2023-02-28                              Chad         7678
47133   2023-02-28                             Chile      5166328
48270   2023-02-28                             China      2023904
49363   2023-02-28                          Colombia      6357173
50401   2023-02-28                           Comoros         8998
51485   2023-02-28                             Congo        25077
52137   2023-02-28                      Cook Islands         7020
53230   2023-02-28                        Costa Rica      1199055
54318   2023-02-28                     Cote d'Ivoire        88197
55421   2023-02-28                           Croatia      1268992
56508   2023-02-28                              Cuba      1112598
57593   2023-02-28                           Curacao        45986
58683   2023-02-28                            Cyprus       649093
59781   2023-02-28                           Czechia      4609820
60869   2023-02-28      Democratic Republic of Congo        95646
61995   2023-02-28                           Denmark      3403360
63076   2023-02-28                          Djibouti        15690
64153   2023-02-28                          Dominica        15760
65251   2023-02-28                Dominican Republic       660533
66349   2023-02-28                           Ecuador      1056578
67463   2023-02-28                             Egypt       515698
68543   2023-02-28                       El Salvador       201785
69622   2023-02-28                           England          NaN
70704   2023-02-28                 Equatorial Guinea        17229
71782   2023-02-28                           Eritrea        10189
72907   2023-02-28                           Estonia       615119
73992   2023-02-28                          Eswatini        74199
75078   2023-02-28                          Ethiopia       499986
76214   2023-02-28                            Europe    247953546
77350   2023-02-28                    European Union    183891709
78445   2023-02-28                    Faeroe Islands        34658
79509   2023-02-28                  Falkland Islands         1930
80638   2023-02-28                              Fiji        68889
81768   2023-02-28                           Finland      1462169
82903   2023-02-28                            France     39662332
83989   2023-02-28                  French Polynesia        77957
85074   2023-02-28                             Gabon        48981
86156   2023-02-28                            Gambia        12586
87258   2023-02-28                           Georgia      1825598
88390   2023-02-28                           Germany     38168908
89475   2023-02-28                             Ghana       171172
90570   2023-02-28                         Gibraltar        20423
91672   2023-02-28                            Greece      5548487
92755   2023-02-28                         Greenland        11971
93832   2023-02-28                           Grenada        19680
95772   2023-02-28                         Guatemala      1236406
97553   2023-02-28                            Guinea        38267
98627   2023-02-28                     Guinea-Bissau         8953
99714   2023-02-28                            Guyana        73069
100793  2023-02-28                             Haiti        34143
101930  2023-02-28                       High income    430907905
103018  2023-02-28                          Honduras       472116
104154  2023-02-28                         Hong Kong      2876106
105250  2023-02-28                           Hungary      2194969
106350  2023-02-28                           Iceland       209093
107479  2023-02-28                             India     44687837
108576  2023-02-28                         Indonesia      6736046
109697  2023-02-28                     International          721
110806  2023-02-28                              Iran      7567906
111910  2023-02-28                              Iraq      2465545
113009  2023-02-28                           Ireland      1703244
114088  2023-02-28                       Isle of Man        38008
115196  2023-02-28                            Israel      4799274
116324  2023-02-28                             Italy     25576852
117412  2023-02-28                           Jamaica       154065
118549  2023-02-28                             Japan     33227230
120332  2023-02-28                            Jordan      1746997
121418  2023-02-28                        Kazakhstan      1498668
122511  2023-02-28                             Kenya       342912
123166  2023-02-28                          Kiribati         5013
124251  2023-02-28                            Kosovo       273059
125355  2023-02-28                            Kuwait       663456
126436  2023-02-28                        Kyrgyzstan       206633
127511  2023-02-28                              Laos       218015
128613  2023-02-28                            Latvia       975999
129720  2023-02-28                           Lebanon      1231840
130745  2023-02-28                           Lesotho        34790
131827  2023-02-28                           Liberia         8077
132922  2023-02-28                             Libya       507174
134017  2023-02-28                     Liechtenstein        21421
135097  2023-02-28                         Lithuania      1304750
136202  2023-02-28                        Low income      2286632
137339  2023-02-28               Lower middle income     97141828
138444  2023-02-28                        Luxembourg       315945
139581  2023-02-28                             Macao         3514
140660  2023-02-28                        Madagascar        67865
141730  2023-02-28                            Malawi        88681
142865  2023-02-28                          Malaysia      5042791
143956  2023-02-28                          Maldives       185732
145030  2023-02-28                              Mali        33018
146124  2023-02-28                             Malta       117477
147155  2023-02-28                  Marshall Islands        15598
148240  2023-02-28                        Mauritania        63667
149321  2023-02-28                         Mauritius       295440
150479  2023-02-28                            Mexico      7451429
151251  2023-02-28              Micronesia (country)        23671
152342  2023-02-28                           Moldova       603750
153441  2023-02-28                            Monaco        16106
154530  2023-02-28                          Mongolia      1007896
155612  2023-02-28                        Montenegro       288280
156693  2023-02-28                        Montserrat         1403
157814  2023-02-28                           Morocco      1272454
158891  2023-02-28                        Mozambique       233098
159963  2023-02-28                           Myanmar       633918
161048  2023-02-28                           Namibia       171156
161743  2023-02-28                             Nauru         5247
162877  2023-02-28                             Nepal      1001145
163978  2023-02-28                       Netherlands      8607173
165058  2023-02-28                     New Caledonia        80007
166158  2023-02-28                       New Zealand      2217640
167238  2023-02-28                         Nicaragua        15627
168317  2023-02-28                             Niger         9508
169417  2023-02-28                           Nigeria       266593
171039  2023-02-28                     North America    122292407
172062  2023-02-28                       North Korea            1
173164  2023-02-28                   North Macedonia       346852
174953  2023-02-28                  Northern Ireland          NaN
176664  2023-02-28                            Norway      1479032
177798  2023-02-28                           Oceania     13996412
178902  2023-02-28                              Oman       399449
180005  2023-02-28                          Pakistan      1576998
180564  2023-02-28                             Palau         5988
181658  2023-02-28                         Palestine       703228
182748  2023-02-28                            Panama      1031273
183827  2023-02-28                  Papua New Guinea        46792
184919  2023-02-28                          Paraguay       808327
186012  2023-02-28                              Peru      4486034
187141  2023-02-28                       Philippines      4076307
188677  2023-02-28                            Poland      6419480
189775  2023-02-28                          Portugal      5566708
191714  2023-02-28                             Qatar       494056
192816  2023-02-28                           Romania      3340342
193944  2023-02-28                            Russia     21960719
195029  2023-02-28                            Rwanda       133180
195937  2023-02-28                      Saint Helena         2166
197011  2023-02-28             Saint Kitts and Nevis         6596
198096  2023-02-28                       Saint Lucia        29882
199159  2023-02-28         Saint Pierre and Miquelon         3452
200244  2023-02-28  Saint Vincent and the Grenadines         9589
201080  2023-02-28                             Samoa        16607
202179  2023-02-28                        San Marino        23536
203241  2023-02-28             Sao Tome and Principe         6281
204338  2023-02-28                      Saudi Arabia       829478
206526  2023-02-28                           Senegal        88917
207628  2023-02-28                            Serbia      2492563
208712  2023-02-28                        Seychelles        50665
209780  2023-02-28                      Sierra Leone         7760
210916  2023-02-28                         Singapore      2226397
212654  2023-02-28                          Slovakia      2665303
213780  2023-02-28                          Slovenia      1328222
214653  2023-02-28                   Solomon Islands        24575
215736  2023-02-28                           Somalia        27324
216857  2023-02-28                      South Africa      4063573
217963  2023-02-28                     South America     67908020
219100  2023-02-28                       South Korea     30526012
220163  2023-02-28                       South Sudan        18368
221290  2023-02-28                             Spain     13763336
222422  2023-02-28                         Sri Lanka       672030
223508  2023-02-28                             Sudan        63787
224593  2023-02-28                          Suriname        82227
225720  2023-02-28                            Sweden      2697827
226823  2023-02-28                       Switzerland      4412439
227900  2023-02-28                             Syria        57467
229043  2023-02-28                            Taiwan      9970937
230080  2023-02-28                        Tajikistan        17786
231163  2023-02-28                          Tanzania        42823
232318  2023-02-28                          Thailand      4728035
233395  2023-02-28                             Timor        23418
234490  2023-02-28                              Togo        39377
235706  2023-02-28                             Tonga        16801
236791  2023-02-28               Trinidad and Tobago       189296
237886  2023-02-28                           Tunisia      1150962
238974  2023-02-28                            Turkey     17042722
240690  2023-02-28          Turks and Caicos Islands         6551
241366  2023-02-28                            Tuvalu         2805
242444  2023-02-28                            Uganda       170504
243540  2023-02-28                           Ukraine      5693846
244670  2023-02-28              United Arab Emirates      1051998
245799  2023-02-28                    United Kingdom     24370154
246936  2023-02-28                     United States    103439103
248891  2023-02-28               Upper middle income    144843003
249977  2023-02-28                           Uruguay      1034303
251061  2023-02-28                        Uzbekistan       250932
251905  2023-02-28                           Vanuatu        12014
252998  2023-02-28                           Vatican           29
254083  2023-02-28                         Venezuela       551981
255219  2023-02-28                           Vietnam     11526917
256275  2023-02-28                             Wales          NaN
257139  2023-02-28                 Wallis and Futuna         3427
258277  2023-02-28                             World    675215217
259335  2023-02-28                             Yemen        11945
260416  2023-02-28                            Zambia       343012
261495  2023-02-28                          Zimbabwe       263921

In [47]:
df2.shape

(234, 3)

In [49]:
 tot_cases_by_loc = df2.groupby("location")["total_cases"].sum()

In [50]:
tot_cases_by_loc

location
Afghanistan                           209322
Africa                              12518681
Albania                               334391
Algeria                               271441
Andorra                                47866
Angola                                105255
Anguilla                                3904
Antigua and Barbuda                     9106
Argentina                           10044125
Armenia                               446819
Aruba                                  44026
Asia                               210545430
Australia                           11366361
Austria                              5911294
Azerbaijan                            828548
Bahamas                                37491
Bahrain                               707480
Bangladesh                           2037773
Barbados                              106645
Belarus                               994037
Belgium                              4717655
Belize                                 70757
Benin                                  27990
Bermuda                                18799
Bhutan                                 62615
Bolivia                              1193009
Bonaire Sint Eustatius and Saba        11797
Bosnia and Herzegovina                401575
Botswana                              329727
Brazil                              37052936
British Virgin Islands                  7305
Brunei                                277992
Bulgaria                             1296853
Burkina Faso                           22056
Burundi                                53609
Cambodia                              138717
Cameroon                              124392
Canada                               4602806
Cape Verde                             63244
Cayman Islands                         31472
Central African Republic               15368
Chad                                    7678
Chile                                5166328
China                                2023904
Colombia                             6357173
Comoros                                 8998
Congo                                  25077
Cook Islands                            7020
Costa Rica                           1199055
Cote d'Ivoire                          88197
Croatia                              1268992
Cuba                                 1112598
Curacao                                45986
Cyprus                                649093
Czechia                              4609820
Democratic Republic of Congo           95646
Denmark                              3403360
Djibouti                               15690
Dominica                               15760
Dominican Republic                    660533
Ecuador                              1056578
Egypt                                 515698
El Salvador                           201785
England                                    0
Equatorial Guinea                      17229
Eritrea                                10189
Estonia                               615119
Eswatini                               74199
Ethiopia                              499986
Europe                             247953546
European Union                     183891709
Faeroe Islands                         34658
Falkland Islands                        1930
Fiji                                   68889
Finland                              1462169
France                              39662332
French Polynesia                       77957
Gabon                                  48981
Gambia                                 12586
Georgia                              1825598
Germany                             38168908
Ghana                                 171172
Gibraltar                              20423
Greece                               5548487
Greenland                              11971
Grenada                                19680
Guatemala                            1236406
Guinea                                 38267
Guinea-Bissau                           8953
Guyana                                 73069
Haiti                                  34143
High income                        430907905
Honduras                              472116
Hong Kong                            2876106
Hungary                              2194969
Iceland                               209093
India                               44687837
Indonesia                            6736046
International                            721
Iran                                 7567906
Iraq                                 2465545
Ireland                              1703244
Isle of Man                            38008
Israel                               4799274
Italy                               25576852
Jamaica                               154065
Japan                               33227230
Jordan                               1746997
Kazakhstan                           1498668
Kenya                                 342912
Kiribati                                5013
Kosovo                                273059
Kuwait                                663456
Kyrgyzstan                            206633
Laos                                  218015
Latvia                                975999
Lebanon                              1231840
Lesotho                                34790
Liberia                                 8077
Libya                                 507174
Liechtenstein                          21421
Lithuania                            1304750
Low income                           2286632
Lower middle income                 97141828
Luxembourg                            315945
Macao                                   3514
Madagascar                             67865
Malawi                                 88681
Malaysia                             5042791
Maldives                              185732
Mali                                   33018
Malta                                 117477
Marshall Islands                       15598
Mauritania                             63667
Mauritius                             295440
Mexico                               7451429
Micronesia (country)                   23671
Moldova                               603750
Monaco                                 16106
Mongolia                             1007896
Montenegro                            288280
Montserrat                              1403
Morocco                              1272454
Mozambique                            233098
Myanmar                               633918
Namibia                               171156
Nauru                                   5247
Nepal                                1001145
Netherlands                          8607173
New Caledonia                          80007
New Zealand                          2217640
Nicaragua                              15627
Niger                                   9508
Nigeria                               266593
North America                      122292407
North Korea                                1
North Macedonia                       346852
Northern Ireland                           0
Norway                               1479032
Oceania                             13996412
Oman                                  399449
Pakistan                             1576998
Palau                                   5988
Palestine                             703228
Panama                               1031273
Papua New Guinea                       46792
Paraguay                              808327
Peru                                 4486034
Philippines                          4076307
Poland                               6419480
Portugal                             5566708
Qatar                                 494056
Romania                              3340342
Russia                              21960719
Rwanda                                133180
Saint Helena                            2166
Saint Kitts and Nevis                   6596
Saint Lucia                            29882
Saint Pierre and Miquelon               3452
Saint Vincent and the Grenadines        9589
Samoa                                  16607
San Marino                             23536
Sao Tome and Principe                   6281
Saudi Arabia                          829478
Senegal                                88917
Serbia                               2492563
Seychelles                             50665
Sierra Leone                            7760
Singapore                            2226397
Slovakia                             2665303
Slovenia                             1328222
Solomon Islands                        24575
Somalia                                27324
South Africa                         4063573
South America                       67908020
South Korea                         30526012
South Sudan                            18368
Spain                               13763336
Sri Lanka                             672030
Sudan                                  63787
Suriname                               82227
Sweden                               2697827
Switzerland                          4412439
Syria                                  57467
Taiwan                               9970937
Tajikistan                             17786
Tanzania                               42823
Thailand                             4728035
Timor                                  23418
Togo                                   39377
Tonga                                  16801
Trinidad and Tobago                   189296
Tunisia                              1150962
Turkey                              17042722
Turks and Caicos Islands                6551
Tuvalu                                  2805
Uganda                                170504
Ukraine                              5693846
United Arab Emirates                 1051998
United Kingdom                      24370154
United States                      103439103
Upper middle income                144843003
Uruguay                              1034303
Uzbekistan                            250932
Vanuatu                                12014
Vatican                                   29
Venezuela                             551981
Vietnam                             11526917
Wales                                      0
Wallis and Futuna                       3427
World                              675215217
Yemen                                  11945
Zambia                                343012
Zimbabwe                              263921
Name: total_cases, dtype: float64